# Generated by Django 4.1.1 on 2022-09-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music_App', '0003_alter_userdetails_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='emotion',
        ),
    ]
